### ISSUE TITLE
Scala 3?

### ISSUE THREAD

**Issue by tsuckow** [codingwell/scala-guice#97]
https://www.scala-lang.org/blog/2021/05/14/scala3-is-here.html

**Comment by cacoco** [comment]
@tsuckow FWIW, the latest Scala 2.13.x (2.13.6) release is compatible with Scala 3 and meant to make the transition to Scala 3 easier. We recently [moved to support Scala 2.13.6](https://github.com/twitter/finatra/commit/52827c7221ae0da50f37165cdae9d06cf4e3775a) because of this.

Also, out of curiosity, it looks like scala-guice still supports Scala 2.11 -- what are the plans (if any) to drop support there as that may make things more complicated to prepare for Scala 3?

**Comment by tsuckow** [comment]
At this point I would consider 2.11 support expendable. I just haven't had anything come up that breaks it.

My initial glances seemed to indicate compiling for Scala 3 would require breaking changes. At which point dropping 2.x is unavoidable anyway.

**Comment by cacoco** [comment]
@tsuckow added support for 2.13.6 in #98. Please take a look.

**Comment by tsuckow** [comment]
2.13.6 seems to get us closer but unfortunately it seems the biggest hurdle is the lack of TypeTags in 3. Attempting to use the 2.13 version of the reflection library would pull in the 2.13 scala library jar which from what I've read is a no-no. (Doesn't work anyway you get an error: "No TypeTag available for Nothing")

![image](https://user-images.githubusercontent.com/262439/133896738-fcd42b34-0b20-403a-8014-86154726e795.png)

It seems it would probably require a macroized version of TypeConversions, assuming that is even possible.

Edit: This is in regards to making a native 3.0 library. I have not tested using the 2.13 version of scala-guice in 3.0.

**Comment by tsuckow** [comment]
5.1.1 should sync to maven central shortly

**Comment by tsuckow** [comment]
![image](https://github.com/codingwell/scala-guice/assets/262439/6a5c9eff-b055-48b3-b556-b1706b32a607)
![image](https://github.com/codingwell/scala-guice/assets/262439/67ba5dcd-c2b8-4de6-b188-33710a73e6f5)
![image](https://github.com/codingwell/scala-guice/assets/262439/3a70af35-2911-4c49-964b-abd2eddc3e7e)
![image](https://github.com/codingwell/scala-guice/assets/262439/145d2962-3763-4bc6-ac0d-1aee71f90079)
